### ISSUE TITLE
Unfinished documentation and english language

### ISSUE THREAD

**Issue by coleblackman** [BrailleRapSP/BrailleRapSP#2]
Hi. I have completed a build using this documentation (with a team) as a guide and would like to contribute to completing the documentation and polishing the instruction guide with more pictures and diagrams and better english language support. I also have input on design improvements that our team came up with during the build process.
---
Sometimes maintainers don't like PRs, so would you prefer that I fork this project instead?

thanks

**Comment by ghost** [comment]
_Affirmative_ 

I second this motion

**Comment by crocsg** [comment]
Hi
feel free to make a pull request and suggest improvements in a new branch.
Also keep in mind that translation is automated in .po files so i think we need to improve both languages to keep it consistent.

**Comment by coleblackman** [comment]
Hi. We decided to heavily modify the documentation focusing on beginners in English and have thus created a new project, braille3d. This project is focused on explaining the details of each build step for people new to the field, to make it more accessible and complete. We believe these documentation projects can coexist. This is released under the same licensing schemes as BrailleRap-SP.

The advantages of this approach: 
- Native English documentation, no need for translation files or multiple versions of the code
- 2 branches of a very similar project, oriented for different skill levels
- revitalize the progress on the project
- a chance to apply our experience from building to streamline the documentation and polish some areas
- Creative control to minimize conflict with the original maintainers

Thanks for the great work and design, it was a pleasure to build.
